### ISSUE TITLE
SCD30 on QT Py giving memory allocation failed

### ISSUE THREAD

**Issue by HB-Git** [adafruit/Adafruit_CircuitPython_SCD30#1]
I tried to connect the SCD30 to a QT py through I2C in MU 1.0.3 I got the following error:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
MemoryError: memory allocation failed, allocating 232 bytes

Press any key to enter the REPL. Use CTRL-D to reload.

The code used for main.py is the scd30_simpletest.py

**Comment by ladyada** [comment]
are you using the mpy for the library file?

**Comment by HB-Git** [comment]
Oh my.. I'm really sorry, I used the .py version which my first link pointed to. 
I now took the .mpy version for CircuitPython 6.x and now the communication started with the QT py!
Thank you!

**Comment by ladyada** [comment]
all good, thanx for testing :)
