### ISSUE TITLE
Errno 19 for few minutes run

### ISSUE THREAD

**Issue by cw1812** [adafruit/Adafruit_CircuitPython_SCD30#12]
File "adafruit_scd30.py", line 183, in CO2
  File "adafruit_scd30.py", line 234, in _read_data
  File "adafruit_scd30.py", line 221, in _send_command
  File "adafruit_scd30.py", line 221, in _send_command
OSError: [Errno 19] Unsupported operation

**Comment by ladyada** [comment]
please post in forums, with *detailed information*

**Comment by kevinjwalters** [comment]
The forum post for this is [Adafruit Forums: Errno19 after few minutes running](https://forums.adafruit.com/viewtopic.php?f=58&t=177465).

There's a slightly different SCD-30 with Pi 4 issue reported on [Adafruit Forums: SCD-30 I2C detection error on Raspberry Pi 4B](https://forums.adafruit.com/viewtopic.php?f=60&t=178335).
