### ISSUE TITLE
Measurement interval setter

### ISSUE THREAD

**Issue by BootNeos** [adafruit/Adafruit_CircuitPython_SCD30#17]
The measurement interval setter works perfectly for the current execution...but if I start the 'usage example' a second time, the measurement interval is set to 2 again. 

Am I missing something? (Because the constructor sets the interval to 2 and I am not able to bypass this) 

Many thanks in advance.

**Comment by jposada202020** [comment]
According to the datasheet the 2 sec interval is the default value, also as you mentioned we set this value in the initialization code.  When you setup the interval to another value does this not change.
Just to clarify if you run the example code a second time, the class will be created again and the time interval will be set to 2 secs:
https://github.com/adafruit/Adafruit_CircuitPython_SCD30/blob/259e369076df04b1ed101ddf46c3ed5da16ab3c6/adafruit_scd30.py#L98

Thanks
