### ISSUE TITLE
Code works in terminal but not in Thonny

### ISSUE THREAD

**Issue by Rastisan** [adafruit/Adafruit_CircuitPython_SCD30#23]
Hi,

I got into the world of Arduino and raspi during Corona so Im quite a noob, especially with raspi.

I cant get the SCD30 to work on raspi and I dont know wether this is because of this particular library or Circuit Python more generally. Please see the attached print screen and explain what is going on.

As you can see, the code works in terminal but not in Thonny.  Why is this so?

It is something to do administrative rights: In terminal the program is initialized with "sudo python3" command in Thonny i maybe not. The "permision denied" in the last line of error msg makes me wonder if the problem is here. 

Some maybe relevant context: 
- Both programs are initialised by user "pita" which is supposed to have the same rights as the default and locked for security reasons "pi" 
- the code in terminal is executed via ssh from my PC to raspi, Thonny code is executed via VNC.
- during instalation of Adafruit Blinka library the blinkatest.py code did not work until I ran it with sudo

Thank you very much!
Rastko

**Comment by ladyada** [comment]
Hi there, for help with running Python, please post to user forums. For example, if its a Raspberry Pi - there's forums at https://forums.raspberrypi.com/ - if its a product purchased from adafruit, there's forums.adafruit.com/ - etc!
